# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commitbrief < Formula
  desc "LLM-powered local code review CLI"
  homepage "https://github.com/CommitBrief/commitbrief"
  version "0.9.2"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CommitBrief/commitbrief/releases/download/v0.9.2/commitbrief_0.9.2_darwin_x86_64.tar.gz"
      sha256 "889ec14ae741f7d9ed0392ebe9f3efdae73a8088c4d4aad999c20041bbcc30ac"

      define_method(:install) do
        bin.install "commitbrief"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CommitBrief/commitbrief/releases/download/v0.9.2/commitbrief_0.9.2_darwin_arm64.tar.gz"
      sha256 "ce454faa9f51cb67eb4e2fe81765715a9e25340280ecec820db5d7ab4c7d80d0"

      define_method(:install) do
        bin.install "commitbrief"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CommitBrief/commitbrief/releases/download/v0.9.2/commitbrief_0.9.2_linux_x86_64.tar.gz"
      sha256 "59bd3edb3b2b3264bcb5fd7400a6e6282994b5492f24ddbed6d3792211d1f6c4"
      define_method(:install) do
        bin.install "commitbrief"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CommitBrief/commitbrief/releases/download/v0.9.2/commitbrief_0.9.2_linux_arm64.tar.gz"
      sha256 "43289b7c085e49385b4f5b91401c7426a7b781bacdfdd5e95737732005ea9db5"
      define_method(:install) do
        bin.install "commitbrief"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system "#{bin}/commitbrief", "--help"
  end
end
